### ISSUE TITLE
Scroll issue in register page in mobile view

### ISSUE THREAD

**Issue by Kin-Kazu** [lemeow125/EquipmentTracker-Frontend#11]
While typing all the inputfields in the register page, I noticed that I cannot scroll up to see the inputs in the area of password and confirm password. I have to manually minimize the mobile keyboard to see the inputs inside. 

![inbound2011488269180079124](https://github.com/lemeow125/EquipmentTracker-Frontend/assets/49527671/d0e71e6a-ba6d-44a2-9f57-eea8b13250d4)

**Comment by lemeow125** [comment]
Messenger browser view is broken. Please use proper browser view for best results

https://github.com/lemeow125/EquipmentTracker-Frontend/assets/63192778/08a6dad6-bded-4ebf-b62e-8ea85e31e3a4
