### ISSUE TITLE
Icon Button of Dashboard and Logout Not Functioning 

### ISSUE THREAD

**Issue by a-r-santos** [lemeow125/EquipmentTracker-Frontend#15]
Issue description: When attempting to press the dashboard and logout icons, it will not go to dashboard and logout. Only the text dashboard and logout is functioning.

Steps:

Open the app and navigate to the login page.
Log in with valid credentials.
Once logged in, it redirects to the dashboard page.
In the dashboard, locate the "equipment" and "logs" section.
Click on the either "View All", "View Skus", "Workstations", "Networking", "CCTVs", "Furniture", "Sku Logs" and "Item Logs"  option within the "equipment" and "logs section.
Click the "menu button located in the left side and kindly click the dashboard icon and logout icon.
Notice that the page is not heading back to dashboard and logout the account and back to login page.

Environment:
BROWSER: Chrome
PLATFORM: Mobile and Web

**Comment by lemeow125** [comment]
https://github.com/lemeow125/EquipmentTracker-Frontend/assets/63192778/458cfc8c-887b-466b-821a-7bfa2f0269b9

Issue cannot be replicated on desktop Firefox/Chrome but is seen in Firefox/Chrome mobile

**Comment by a-r-santos** [comment]
Click the Icon itself like this one. 

https://github.com/lemeow125/EquipmentTracker-Frontend/assets/102279525/59b19021-3e4c-4a89-9fe2-95857fdaa131

**Comment by lemeow125** [comment]
Fixed as of commit ab2525ad95e31d8b5e0f3e1ca886c77a7bdeb917

**Comment by a-r-santos** [comment]
Can we centered the text "Dashboard" and "Log-out"?

**Comment by lemeow125** [comment]
Please raise a separate issue for your suggestion for better transparency or create your own pull request with your own commit to address the requested change
