### ISSUE TITLE
Dashboard and Logout in the Menu Bar is not Centered

### ISSUE THREAD

**Issue by a-r-santos** [lemeow125/EquipmentTracker-Frontend#16]
Issue description: The "Dashboard" and "Logout" Text is not centered in the menu bar.

Steps:

Open the app and navigate to the login page.
Log in with valid credentials.
Once logged in, it redirects to the dashboard page.
In the dashboard, locate the "equipment" and "logs" section.
Click on the either "View All", "View Skus", "Workstations", "Networking", "CCTVs", "Furniture", "Sku Logs" and "Item Logs" option within the "equipment" and "logs section.
Click the "menu button located in the left side.
Notice that the "Dashboard" and "Logout" text is not centered.

Environment:
BROWSER: Chrome
PLATFORM: Mobile and Web

**Comment by lemeow125** [comment]
![image](https://github.com/lemeow125/EquipmentTracker-Frontend/assets/63192778/1165eb43-8101-46c3-9800-48b827ec8de1)

Labels look out of place when centered

**Comment by lemeow125** [comment]
![image](https://github.com/lemeow125/EquipmentTracker-Frontend/assets/63192778/e392581b-16f0-4d49-82aa-9449844a2a44)

A better rework would be to reduce the button container's width to make the button not seem empty

**Comment by a-r-santos** [comment]
I think the centered one is much better

**Comment by Kin-Kazu** [comment]
Much better if the color of the card box is something similar to the base color, but not the same. 

Here's the sample picture of what I meant. 

![inbound2070844696430024086](https://github.com/lemeow125/EquipmentTracker-Frontend/assets/49527671/fcbe148f-773d-4f6f-8e3f-6d42db3f5850)

The design is already looking good. I think that would be my suggestion/s until I could come up something great ideas. Thanks for reading!

**Comment by lemeow125** [comment]
Current suggestion is not possible due to https://github.com/lemeow125/EquipmentTracker-Frontend/issues/15.

**Comment by lemeow125** [comment]
@a-r-santos your suggestion of centering the text in the drawer button would conflict with conventional UI/UX design. Please see the photo attached by @Kin-Kazu. Text is not centered, but instead is aligned left to appear uniform regardless of length

**Comment by lemeow125** [comment]
![image](https://github.com/lemeow125/EquipmentTracker-Frontend/assets/63192778/b8dcbaba-7d62-4ffb-a4e4-b804ef4e3f1b)

As per suggestion by @Preyness, the button width has been reduced further to appear less empty. Please see commit 7333db59a43043ff2cc47baf55b76c7ebe38f8f3. I will be closing this issue.
